[tool.poetry]
name = "tidal_marsh"
version = "0.1.0"
description = "A zero-dimensional morphodynamic model of tidal marsh elevation."
authors = ["Chris Tasich <chris.tasich@vanderbilt.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.23.3"
pandas = "^1.4.4"
seaborn = "^0.12.0"
loguru = "^0.6.0"
tqdm = "^4.64.1"
scipy = "^1.9.1"
matplotlib = "^3.5.3"
statsmodels = "^0.13.2"
joblib = "^1.1.0"
sklearn = "^0.0"
pyarrow = "^9.0.0"
plotly = "^5.5.0"
psutil = "^5.9.0"
UTide = "^0.3.0"
vtk = {path = "/home/chris/vtk-9.1.0.dev0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"}
pyvista = "^0.36.1"

[tool.poetry.dev-dependencies]
flake8 = "^5.0.4"
pre-commit = "^2.20.0"
black = "^22.8.0"
mypy = "^0.971"
ipympl = "^0.9.2"
jupyter-dash = "^0.4.0"
memory-profiler = "^0.60.0"
autopep8 = "^1.7.0"
ipywidgets = "^7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
