[tool.poetry]
name = "tidal_marsh"
version = "0.1.0"
description = "A zero-dimensional morphodynamic model of tidal marsh elevation."
authors = ["Chris Tasich <chris.tasich@vanderbilt.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.22.1"
pandas = "^1.4.0"
seaborn = "^0.11.2"
loguru = "^0.5.3"
tqdm = "^4.62.3"
scipy = "^1.7.3"
matplotlib = "^3.5.1"
UTide = "^0.2.6"
statsmodels = "^0.13.1"
joblib = "^1.1.0"
sklearn = "^0.0"
pyarrow = "^6.0.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^21.12b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
