[tool.poetry]
name = "tidal_marsh"
version = "0.1.0"
description = "A zero-dimensional morphodynamic model of tidal marsh elevation."
authors = ["Chris Tasich <chris.tasich@vanderbilt.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
numpy = "^1.22.1"
pandas = "^1.4.0"
seaborn = "^0.11.2"
loguru = "^0.5.3"
tqdm = "^4.62.3"
scipy = "^1.7.3"
matplotlib = "^3.5.1"
UTide = "^0.2.6"
statsmodels = "^0.13.1"
joblib = "^1.1.0"
sklearn = "^0.0"
pyarrow = "^6.0.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
pre-commit = "^2.17.0"
black = {version = "^21.12b0", allow-prereleases = true}
ipykernel = "^6.7.0"
mypy = "^0.931"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
line_length = 120

[tool.black]
line-length = 120
target-version = ['py38']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | foo.py           # also separately exclude a file named foo.py in
                     # the root of the project
)
'''
