#     init_elevation,
#     water_levels,
#     ssc,
#     bulk_density,
#     grain_diameter,
#     grain_density=2.65e3,
#     slr=0.0,
#     deep_sub=0.0,
#     disable_pbar=False,
#     compile_results=True,

workspace:
  path: ./results
  overwrite: False

multiprocessing:
  enabled: True
  max_cores: 60

tides:
  path: data/processed/tides-pickle/1900-2099_5T_nodal.pickle

platform:
  init_elevation: 1.0
  ssc: 0.5
  grain_diameter: 25.0e-6
  grain_density: 2.65e+3
  bulk_density: 1000.0
  org_sed: 0.0
  compaction: 0.0
  deep_sub: 0.0

# workspace:
#   path: ./results
#   overwrite: False

# cache:
#   path: ./data/.cache/4-delta
#   rebuild: False

# multiprocessing:
#   enabled: True
#   max_cores: 60

# logging:
#   enabled: True
#   handlers:
#     - type: stderr
#       enabled: False
#       config:
#         level: DEBUG
#         colorize: True
#         backtrace: False
#         diagnose: True
#     - type: file
#       enabled: True
#       config:
#         level: DEBUG
#         mode: w
#         backtrace: True
#         diagnose: True
#         serialize: True

# tides:
#   path: data/processed/tides_1960-2052.pickle
#   params:
#     rslr: [0.000, 0.002, 0.004, 0.006, 0.008, 0.010]
#     mtr: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# platform:
#   initial_elevation: 1.0
#   ssc: [0.001, 0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
#   grain_diameter: 25.0e-6 # [15.0e-6, 25.0e-6, 35.0e-6]
#   grain_density: 2.65e+3
#   bulk_density: 1000 #[700, 1000, 1300]
#   organic_rate: 0 #[0.0, 0.5e-3, 1.0e-3]
#   compaction_rate: 0 #[-5.0e-3, -10.0e-3, -15.0e-3]
#   subsidence_rate: 0 #[-2.0e-3, -2.5e-3, -3.0e-3]
